name: 'Run slither'
on:
  workflow_dispatch:
  pull_request:
jobs:
  gas_profiler:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install packages
        run: pip install slither-analyzer

      - name: Install solc
        run: sudo add-apt-repository ppa:ethereum/ethereum;sudo add-apt-repository ppa:ethereum/ethereum-dev;sudo apt-get update;sudo apt-get install solc

      - name: Slither analysis
        run: slither-check-upgradeability contracts/Configurator.sol Configurator --proxy-filename contracts/TransparentUpgradeableConfiguratorProxy.sol --proxy-name TransparentUpgradeableConfiguratorProxy
